package imagetools.view;

import imagetools.controller.IController;

/**
 * This is the interface for a View Object that houses a GUI for an image processing application.
 * The way the GUI is formatted doesn't truly matter, but in the least, it should display an image,
 * a
 */
public interface IView {

  /**
   * Repaints the image based on a new 3D array generated by the model.
   * @param img newly generated 3D array.
   */
  public void setImg(int[][][] img);


  /**
   * The view needs to be able to display an image (make it visible).
   */
  void display();


  /**
   * Exits out of program
   */
  void exit();

  /**
   * Sets action listener to this view.
   * @param listener action listener that completes operations for this view.
   */
  void setListener(IController listener);

  /**
   * Tells view that an illegal option was selected in application. View should display
   * this message.
   *
   * @param message The message to be displayed.
   */
  void errorOption(String message);

}
